# 设置前缀
set -g prefix C-a
unbind M-a
bind C-a send-prefix
#unbind C-a
#set-option -g prefix C-b
#bind-key C-b send-prefix

# 去掉默认前缀
#unbind C-a
# 把前缀改成 Alt-a
#set -g prefix M-a
# 如果你在 tmux 里面再嵌套 tmux，可以把前缀发送进去
#bind-key M-a send-prefix


# 启用插件管理器
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

# 基本配置
set -g mouse on
set -g history-limit 9999999

# 滚动时不自动跳回底部，选中的内容保持选中
set -g @scroll-down-exit-copy-mode "off"
set -g @scroll-without-changing-pane "on"

# 鼠标拖动选择后不退出复制模式（关键修复）
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-no-clear
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection-no-clear

# 初始化 TPM（最后一行）
run -b '~/.tmux/plugins/tpm/tpm'


# 关键设置：允许转义序列透传 (Tmux 3.3a+ 必须)
#set -g allow-passthrough on

# 开启剪贴板功能, nvim 套娃的时候用的
set -s set-clipboard on

# 真彩色支持（让终端色彩完美传递进 tmux）
set -g default-terminal "tmux-256color"
set -as terminal-features ",tmux-256color:RGB"


# 开启真彩色 (True Color) 支持
set-option -ga terminal-overrides ",tmux-256color:Tc"
